### ISSUE TITLE
Compatibly

### ISSUE THREAD

**Issue by 2f-Wheaty** [OlivierGaland/CashFactory#15]
#### Raspberry pi?
So I began running this on my old laptop and it works pretty well, I have a few raspberry pi's on the way (for other projects) but it got me thinking, if you got a raspberry pi 3b+ could you run it and get a 1 month ROI (return on investment)? I understand that raspberry pi's can run 32 or 64 bit operating systems but the arm processor is questionable. I also understand that some of the programs used do not support arm as well but you could add things like [Mysterium](https://www.mysterium.network).
##### Just a thought I thought would be worth sharing, please no hate.

**Comment by OlivierGaland** [comment]
Someone managed to run the stack on a Pi (see Discussions), but only earnapp and honeygain are working, the others don't have a arm image.

I have currently not enough time to check more  for the Pi, but I may deliver a docker-compose for it specifically (basically removing all sections from the current one except earnapp and honeygain), in any case only honeygain and earnapp will  be available with this method, until the apps providers release an arm image.

With only those 2 apps running, you may expect around $10-$15 per monthes, not enough to ROI it in 1 month.

**Comment by 2f-Wheaty** [comment]
That sounds cool, not the assumed on month with the $35 option but 2 months sounds kinda good. Once I get a new Pi I can fork this a update for just the raspberry pi.

**Comment by OlivierGaland** [comment]
Btw I'm also running a mysterium node for evaluation since a few week as a standalone image, issue is the installation which is not easy as other packages (need to deposit a fee to open the node) and mainly the payment is done in MYST, a crypto which is not listed on many exchange, this is not straight forward to get money from it.

It could be included in the future, but I should make lots of work on the documentation as it need to explain crypto, exchanges, swapping to use it.

I'm also facing some issues on the dockerized myst node, I had to run it with --hosts to force the container to use my local network, if I'm not doing it there is some traffic routing issue between the docker swarm and internet.
By the way even with a configuration that seems correct, my node is still flagged with limited connectivity (saying nat : symetrical) and so far income is very low for me, I got only 0.5 MYST over the past 10 days which is around $0.15

**Comment by 2f-Wheaty** [comment]
I understand the problems with documentation and setting up. I could make it easier for you by maybe creating a video tutorial and you could just include that.

For the Mysterium node, If I'm not mistaken there is a certain amount of free account that can be made per day, so something using web automation to create an account at the start of a day? That would likely be a violation of TOS though...

It seems quite odd that mysterium would limit from a docker container but I can look for other things like it, another node service?, a crypto node? I do see the same problem with a crypto node and the space needed on a drive of some sort

Just another question, would also selling cpu power work? or just extra internet? It would be cool to start a cloud hosting service to pay out others for running.

**Comment by OlivierGaland** [comment]
Hello,

For mysterium I'm not sure the free account are still possible, and as you said, if we automatize that it would be considered as an abuse (and would be hard to code). I did some changes on my routing and managed to get it working as "no limited" even under docker.

I stick to unused bandwidth as it is the only ressource I have ( my cpu and gpu are already working ;) ).
